name: 'TestNG Report'
description: 'Report TestNG test results as annotations on Github Pull Request'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  report_paths:
    description: 'Testng xml report paths in glob format'
    required: false
    default: '**/testng-results.xml'
  update_existing_check:
    description: 'Update existing check with annotations'
    required: false
    default: false
  remove_duplicates:
    description: 'Remove duplicated test failures'
    required: false
    default: true
  show_skipped:
    description: 'Show count of skipped and ignored tests'
    required: false
    default: false
  check_name:
    description: 'Check name to report status to'
    required: false
    default: 'Test Report'
  fail_if_empty:
    description: 'Fail check if test reports are empty or not found'
    required: false
    default: true
  commit:
    description: 'commit sha to update the status'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
